/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ISlugRouteImport } from './routes/i.$slug'
import { Route as ContextsNewRouteImport } from './routes/contexts.new'
import { Route as ContextsIdRouteImport } from './routes/contexts.$id'
import { Route as ContextsIdReviewRouteImport } from './routes/contexts.$id.review'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ISlugRoute = ISlugRouteImport.update({
  id: '/i/$slug',
  path: '/i/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsNewRoute = ContextsNewRouteImport.update({
  id: '/contexts/new',
  path: '/contexts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsIdRoute = ContextsIdRouteImport.update({
  id: '/contexts/$id',
  path: '/contexts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsIdReviewRoute = ContextsIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ContextsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/contexts/$id': typeof ContextsIdRouteWithChildren
  '/contexts/new': typeof ContextsNewRoute
  '/i/$slug': typeof ISlugRoute
  '/contexts/$id/review': typeof ContextsIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/contexts/$id': typeof ContextsIdRouteWithChildren
  '/contexts/new': typeof ContextsNewRoute
  '/i/$slug': typeof ISlugRoute
  '/contexts/$id/review': typeof ContextsIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/contexts/$id': typeof ContextsIdRouteWithChildren
  '/contexts/new': typeof ContextsNewRoute
  '/i/$slug': typeof ISlugRoute
  '/contexts/$id/review': typeof ContextsIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/contexts/$id'
    | '/contexts/new'
    | '/i/$slug'
    | '/contexts/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/contexts/$id'
    | '/contexts/new'
    | '/i/$slug'
    | '/contexts/$id/review'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/contexts/$id'
    | '/contexts/new'
    | '/i/$slug'
    | '/contexts/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ContextsIdRoute: typeof ContextsIdRouteWithChildren
  ContextsNewRoute: typeof ContextsNewRoute
  ISlugRoute: typeof ISlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$slug': {
      id: '/i/$slug'
      path: '/i/$slug'
      fullPath: '/i/$slug'
      preLoaderRoute: typeof ISlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/new': {
      id: '/contexts/new'
      path: '/contexts/new'
      fullPath: '/contexts/new'
      preLoaderRoute: typeof ContextsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/$id': {
      id: '/contexts/$id'
      path: '/contexts/$id'
      fullPath: '/contexts/$id'
      preLoaderRoute: typeof ContextsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/$id/review': {
      id: '/contexts/$id/review'
      path: '/review'
      fullPath: '/contexts/$id/review'
      preLoaderRoute: typeof ContextsIdReviewRouteImport
      parentRoute: typeof ContextsIdRoute
    }
  }
}

interface ContextsIdRouteChildren {
  ContextsIdReviewRoute: typeof ContextsIdReviewRoute
}

const ContextsIdRouteChildren: ContextsIdRouteChildren = {
  ContextsIdReviewRoute: ContextsIdReviewRoute,
}

const ContextsIdRouteWithChildren = ContextsIdRoute._addFileChildren(
  ContextsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ContextsIdRoute: ContextsIdRouteWithChildren,
  ContextsNewRoute: ContextsNewRoute,
  ISlugRoute: ISlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
